version: '3.8'
services:
  app:
    build:
      context: ./
      target: runner
    ports:
      - "127.0.0.1:3000:3000"
#    expose:
#      - "3000"
#    ports:
#      - "3000:3000"

networks:
  default:
    external: true
    name: proxy
